# Generated by Django 4.0.2 on 2022-03-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_job_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='ordering_number',
            field=models.IntegerField(help_text='Ascending'),
        ),
    ]
