# Generated by Django 4.0.2 on 2022-05-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_alter_testimonial_ordering_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='testimonial',
            managers=[
            ],
        ),
    ]
