# Generated by Django 4.0.2 on 2022-05-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_ordered_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordering_number',
        ),
    ]
