FROM ubuntu:20.04

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    software-properties-common \
    vim \
    curl \
    git \
    gettext

RUN apt-get install -y build-essential python3 python3-dev python3-pip python3-venv libpq-dev

RUN python3 -m pip install --upgrade pip setuptools

RUN mkdir /project
ADD . /project/
WORKDIR /project/

RUN python3 -m pip install -r /project/requirements/requirements.txt
RUN python3 -m pip install -r /project/requirements/requirements-dev.txt
