# Generated by Django 4.0.2 on 2022-03-13 15:21

import core.utils.utils
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering_number', models.IntegerField(help_text='Ascending')),
                ('icon', models.ImageField(upload_to=core.utils.utils.get_file_path)),
                ('name', models.CharField(max_length=500)),
                ('name_en', models.CharField(max_length=500, null=True)),
                ('name_ar', models.CharField(max_length=500, null=True)),
                ('name_de', models.CharField(max_length=500, null=True)),
                ('name_fr', models.CharField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('pobs', django.db.models.manager.Manager()),
            ],
        ),
    ]
