# Generated by Django 4.0.2 on 2022-04-05 21:42

import core.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service(Homepage)', 'verbose_name_plural': 'Services(Homepage)'},
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(upload_to=core.utils.utils.get_file_path),
        ),
    ]
