# Generated by Django 4.0.2 on 2022-04-17 18:08

import core.utils.utils
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering_number', models.IntegerField(help_text='Ascending')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('title_de', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('price_currency', models.CharField(max_length=200)),
                ('price_currency_en', models.CharField(max_length=200, null=True)),
                ('price_currency_ar', models.CharField(max_length=200, null=True)),
                ('price_currency_de', models.CharField(max_length=200, null=True)),
                ('price_currency_fr', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200)),
                ('price_en', models.CharField(max_length=200, null=True)),
                ('price_ar', models.CharField(max_length=200, null=True)),
                ('price_de', models.CharField(max_length=200, null=True)),
                ('price_fr', models.CharField(max_length=200, null=True)),
                ('price_small', models.CharField(blank=True, max_length=200, null=True)),
                ('price_small_en', models.CharField(blank=True, max_length=200, null=True)),
                ('price_small_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('price_small_de', models.CharField(blank=True, max_length=200, null=True)),
                ('price_small_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
            managers=[
                ('pobs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering_number', models.IntegerField(help_text='Ascending')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('title_de', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('price', models.CharField(max_length=200)),
                ('price_en', models.CharField(max_length=200, null=True)),
                ('price_ar', models.CharField(max_length=200, null=True)),
                ('price_de', models.CharField(max_length=200, null=True)),
                ('price_fr', models.CharField(max_length=200, null=True)),
                ('most_popular', models.BooleanField(default=False)),
                ('icon', models.FileField(upload_to=core.utils.utils.get_file_path)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('label_en', models.CharField(blank=True, max_length=200, null=True)),
                ('label_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('label_de', models.CharField(blank=True, max_length=200, null=True)),
                ('label_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
            managers=[
                ('pobs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering_number', models.IntegerField(help_text='Ascending')),
                ('image', models.FileField(upload_to=core.utils.utils.get_file_path)),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('title_de', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Service Slider',
                'verbose_name_plural': 'Services Slider',
            },
            managers=[
                ('pobs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ar', models.CharField(max_length=200, null=True)),
                ('name_de', models.CharField(max_length=200, null=True)),
                ('name_fr', models.CharField(max_length=200, null=True)),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceitem')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ar', models.CharField(max_length=200, null=True)),
                ('name_de', models.CharField(max_length=200, null=True)),
                ('name_fr', models.CharField(max_length=200, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.package')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
