# Generated by Django 4.0.2 on 2022-04-18 19:05

import core.utils.utils
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_package_serviceitem_serviceslider_serviceitemfeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering_number', models.IntegerField(help_text='Ascending')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ar', models.CharField(max_length=200, null=True)),
                ('title_de', models.CharField(max_length=200, null=True)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('subtitle', models.TextField()),
                ('subtitle_en', models.TextField(null=True)),
                ('subtitle_ar', models.TextField(null=True)),
                ('subtitle_de', models.TextField(null=True)),
                ('subtitle_fr', models.TextField(null=True)),
                ('price', models.CharField(max_length=200)),
                ('price_en', models.CharField(max_length=200, null=True)),
                ('price_ar', models.CharField(max_length=200, null=True)),
                ('price_de', models.CharField(max_length=200, null=True)),
                ('price_fr', models.CharField(max_length=200, null=True)),
                ('icon', models.FileField(upload_to=core.utils.utils.get_file_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
            managers=[
                ('pobs', django.db.models.manager.Manager()),
            ],
        ),
    ]
