# Generated by Django 4.0.2 on 2022-05-22 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_slider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.serviceslider'),
        ),
    ]
