# Generated by Django 4.0.2 on 2022-05-23 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_service_slider'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='package',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='service',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='serviceitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='serviceslider',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_slider',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category'),
        ),
    ]
