# Generated by Django 4.0.2 on 2022-06-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_category_managers_alter_package_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceslider',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceslider',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceslider',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceslider',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serviceslider',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
