# Generated by Django 4.0.2 on 2022-08-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_serviceslider_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='most_popular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
