# Generated by Django 4.0.2 on 2022-03-13 11:10

import core.utils.utils
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering_number', models.IntegerField(help_text='Ascending ordering.')),
                ('bg_image', models.ImageField(upload_to=core.utils.utils.get_file_path)),
                ('title', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_ar', models.CharField(max_length=500, null=True)),
                ('title_de', models.CharField(max_length=500, null=True)),
                ('title_fr', models.CharField(max_length=500, null=True)),
                ('subtitle', models.TextField()),
                ('subtitle_en', models.TextField(null=True)),
                ('subtitle_ar', models.TextField(null=True)),
                ('subtitle_de', models.TextField(null=True)),
                ('subtitle_fr', models.TextField(null=True)),
                ('button_text', models.CharField(max_length=100)),
                ('button_text_en', models.CharField(max_length=100, null=True)),
                ('button_text_ar', models.CharField(max_length=100, null=True)),
                ('button_text_de', models.CharField(max_length=100, null=True)),
                ('button_text_fr', models.CharField(max_length=100, null=True)),
                ('button_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('pobs', django.db.models.manager.Manager()),
            ],
        ),
    ]
