# Generated by Django 4.0.2 on 2022-03-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_companyinfo_portfoliopage_shortcut_socialmediapage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name_plural': 'Company info'},
        ),
        migrations.AlterModelOptions(
            name='portfoliopage',
            options={'verbose_name_plural': 'Portfolio page'},
        ),
    ]
