# Generated by Django 4.0.2 on 2022-03-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=100)),
                ('button_text_en', models.CharField(max_length=100, null=True)),
                ('button_text_ar', models.CharField(max_length=100, null=True)),
                ('button_text_de', models.CharField(max_length=100, null=True)),
                ('button_text_fr', models.CharField(max_length=100, null=True)),
                ('subtitle', models.TextField()),
                ('subtitle_en', models.TextField(null=True)),
                ('subtitle_ar', models.TextField(null=True)),
                ('subtitle_de', models.TextField(null=True)),
                ('subtitle_fr', models.TextField(null=True)),
                ('button_link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Service order section',
            },
        ),
    ]
