# Generated by Django 4.0.2 on 2022-04-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_serviceordersection_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Store page',
            },
        ),
    ]
