# Generated by Django 4.0.2 on 2022-04-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_storepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepage',
            name='subtitle_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='storepage',
            name='subtitle_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='storepage',
            name='subtitle_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='storepage',
            name='subtitle_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='storepage',
            name='title_ar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='storepage',
            name='title_de',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='storepage',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='storepage',
            name='title_fr',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
