# Generated by Django 4.0.2 on 2022-04-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_storepage_subtitle_ar_storepage_subtitle_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_ar', models.CharField(max_length=500, null=True)),
                ('title_de', models.CharField(max_length=500, null=True)),
                ('title_fr', models.CharField(max_length=500, null=True)),
                ('subtitle', models.TextField()),
                ('subtitle_en', models.TextField(null=True)),
                ('subtitle_ar', models.TextField(null=True)),
                ('subtitle_de', models.TextField(null=True)),
                ('subtitle_fr', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog page(title, subtitle)',
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_ar', models.CharField(max_length=500, null=True)),
                ('title_de', models.CharField(max_length=500, null=True)),
                ('title_fr', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service page(title)',
            },
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name_plural': 'Company info(footer, contact us'},
        ),
        migrations.AlterModelOptions(
            name='portfoliopage',
            options={'verbose_name_plural': 'Portfolio page(title, subtitle)'},
        ),
        migrations.AlterModelOptions(
            name='storepage',
            options={'verbose_name_plural': 'Store page(title, subtitle)'},
        ),
    ]
