# Generated by Django 4.0.2 on 2022-04-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_blogpage_servicepage_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name_plural': 'Company info(footer, contact us)'},
        ),
        migrations.AlterModelOptions(
            name='serviceordersection',
            options={'verbose_name_plural': 'Order Now Section'},
        ),
    ]
