# Generated by Django 4.0.2 on 2022-04-15 04:49

import core.utils.utils
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_aboutussection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutussection',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='Use this only with `image with text` or `full width image` section types', null=True, upload_to=core.utils.utils.get_file_path),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='button_link',
            field=models.CharField(blank=True, help_text="\n            If it is a link to an external page, please start with http:// or https://.\n            If it is a link to a page on this website, please start with / right after domain and DON'T INCLUDE language.\n        ", max_length=500, null=True, validators=[core.validators.button_link_validator]),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='description',
            field=models.TextField(blank=True, help_text='Use this only with `text` section type', null=True),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='description_ar',
            field=models.TextField(blank=True, help_text='Use this only with `text` section type', null=True),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='description_de',
            field=models.TextField(blank=True, help_text='Use this only with `text` section type', null=True),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='description_en',
            field=models.TextField(blank=True, help_text='Use this only with `text` section type', null=True),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Use this only with `text` section type', null=True),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='image_with_text_type',
            field=models.CharField(blank=True, choices=[('image_left', 'Image left'), ('image_top', 'Image top'), ('image_bottom', 'Image bottom')], help_text='Use this only with `image with text` section type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='title',
            field=models.CharField(blank=True, help_text='Use this only with `text` or `image with text` section types', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Use this only with `text` or `image with text` section types', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='title_de',
            field=models.CharField(blank=True, help_text='Use this only with `text` or `image with text` section types', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='title_en',
            field=models.CharField(blank=True, help_text='Use this only with `text` or `image with text` section types', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='title_fr',
            field=models.CharField(blank=True, help_text='Use this only with `text` or `image with text` section types', max_length=500, null=True),
        ),
    ]
