# Generated by Django 4.0.2 on 2022-04-18 18:27

import core.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_aboutussection_bg_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.FileField(upload_to=core.utils.utils.get_file_path),
        ),
    ]
