# Generated by Django 4.0.2 on 2022-05-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_companyinfo_logo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aboutussection',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='shortcut',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='slider',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='socialmediapage',
            managers=[
            ],
        ),
    ]
