# Generated by Django 4.0.2 on 2022-04-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfoliofile_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioSlider',
        ),
    ]
