# Generated by Django 4.0.2 on 2022-05-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_delete_portfolioslider'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='portfolio',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='portfoliofile',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='portfoliohomepage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='subcategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
    ]
