# Generated by Django 4.0.2 on 2022-05-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_label_color_store_label_text_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='store',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='subcategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
    ]
