# Generated by Django 4.0.2 on 2022-04-02 20:21

import core.utils.utils
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering_number', models.IntegerField(help_text='Ascending')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('name_en', models.CharField(max_length=500, null=True, unique=True)),
                ('name_ar', models.CharField(max_length=500, null=True, unique=True)),
                ('name_de', models.CharField(max_length=500, null=True, unique=True)),
                ('name_fr', models.CharField(max_length=500, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
            managers=[
                ('pobs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering_number', models.IntegerField(help_text='Ascending')),
                ('section_type', models.CharField(choices=[('f', 'Full width image'), ('i', 'Image with paddings'), ('t', 'Text')], max_length=1)),
                ('section_text', models.TextField(blank=True, null=True)),
                ('section_text_en', models.TextField(blank=True, null=True)),
                ('section_text_ar', models.TextField(blank=True, null=True)),
                ('section_text_de', models.TextField(blank=True, null=True)),
                ('section_text_fr', models.TextField(blank=True, null=True)),
                ('section_image', models.ImageField(blank=True, null=True, upload_to=core.utils.utils.get_file_path)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('pobs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering_number', models.IntegerField(help_text='Ascending')),
                ('title', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_ar', models.CharField(max_length=500, null=True)),
                ('title_de', models.CharField(max_length=500, null=True)),
                ('title_fr', models.CharField(max_length=500, null=True)),
                ('author_full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('author_full_name_en', models.CharField(blank=True, max_length=500, null=True)),
                ('author_full_name_ar', models.CharField(blank=True, max_length=500, null=True)),
                ('author_full_name_de', models.CharField(blank=True, max_length=500, null=True)),
                ('author_full_name_fr', models.CharField(blank=True, max_length=500, null=True)),
                ('posted_at', models.DateTimeField()),
                ('categories', models.ManyToManyField(to='posts.Category')),
                ('sections', models.ManyToManyField(to='posts.Section')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('pobs', django.db.models.manager.Manager()),
            ],
        ),
    ]
