# Generated by Django 4.0.2 on 2022-04-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_url_slug_post_url_slug_ar_post_url_slug_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
    ]
