# Generated by Django 4.0.2 on 2022-04-04 13:15

import core.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_sections_section_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=core.utils.utils.get_file_path),
            preserve_default=False,
        ),
    ]
