# Generated by Django 4.0.2 on 2022-05-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_url_slug_ar_remove_post_url_slug_de_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='section',
            managers=[
            ],
        ),
    ]
